// Offline dictionary lookup over two bundled public-domain sources:
//   • Webster's 1913 — general English, period-correct for archaic KJV words.
//   • Easton's 1897 Bible Dictionary — biblical names, places, theology.
//
// Both files are static assets under /public/dictionaries (generated by
// scripts/fetch-dictionaries.mjs) and precached by the service worker, so
// lookups work fully offline after the first load. The data is loaded lazily
// into memory on first use and cached for the lifetime of the tab — exact-key
// access is all we need, so a plain object/Map beats a search index here.

import type { SelectedVerse } from "@/components/slide-stage"

export type DictSource = "websters" | "eastons"

export interface DictEntry {
  word: string
  definition: string
  source: DictSource
}

// Raw on-disk shapes (see scripts/fetch-dictionaries.mjs).
type WebsterFile = Record<string, string>
type EastonFile = Record<string, { w: string; d: string }>

interface Loaded {
  entries: Map<string, DictEntry[]>
  keys: string[] // sorted, for prefix suggestions
}

let loadPromise: Promise<Loaded> | null = null

// Lowercased, trimmed, surrounding-punctuation-stripped. Must match the
// normalization used when the files were generated.
function normalize(word: string): string {
  return word
    .toLowerCase()
    .trim()
    .replace(/^[^a-z]+|[^a-z]+$/g, "")
}

// KJV is full of inflected forms ("cometh", "lovest", "saints"). When an exact
// match misses, retry against a handful of suffix-stripped stems. This is a
// best-effort fallback, not a real lemmatizer — irregulars ("saith" → "say")
// won't resolve, but the common regular inflections do.
function stems(key: string): string[] {
  const out: string[] = []
  const suffixes = ["edst", "eth", "est", "ing", "ed", "es", "th", "s"]
  for (const suf of suffixes) {
    if (key.length > suf.length + 2 && key.endsWith(suf)) {
      const base = key.slice(0, -suf.length)
      out.push(base)
      // "loved" → "love": restore a dropped 'e' after stripping "ed"/"es".
      if (suf === "ed" || suf === "es") out.push(base + "e")
      // "studies" → "study": -ies → -y.
      if (suf === "es" && base.endsWith("i")) out.push(base.slice(0, -1) + "y")
    }
  }
  return out
}

async function load(): Promise<Loaded> {
  if (loadPromise) return loadPromise
  loadPromise = (async () => {
    const [websters, eastons] = await Promise.all([
      fetch("/dictionaries/websters.json").then((r) =>
        r.ok ? (r.json() as Promise<WebsterFile>) : ({} as WebsterFile),
      ),
      fetch("/dictionaries/eastons.json").then((r) =>
        r.ok ? (r.json() as Promise<EastonFile>) : ({} as EastonFile),
      ),
    ])

    const entries = new Map<string, DictEntry[]>()
    const push = (key: string, entry: DictEntry) => {
      const list = entries.get(key)
      if (list) list.push(entry)
      else entries.set(key, [entry])
    }

    for (const [key, def] of Object.entries(websters)) {
      push(key, { word: key, definition: def, source: "websters" })
    }
    for (const [key, { w, d }] of Object.entries(eastons)) {
      push(key, { word: w, definition: d, source: "eastons" })
    }

    return { entries, keys: [...entries.keys()].sort() }
  })()
  return loadPromise
}

// Eagerly start loading (e.g. when the Dictionary pane mounts) so the first
// lookup is instant. Safe to call repeatedly — the promise is memoized.
export function preloadDictionary(): void {
  void load()
}

export interface LookupResult {
  query: string
  matchedKey: string | null
  entries: DictEntry[]
}

// Look a word up across both dictionaries. When both have an entry, biblical
// (Easton's) is ordered first if the original query reads like a proper noun
// (leading capital); otherwise general (Webster's) comes first.
export async function lookup(query: string): Promise<LookupResult> {
  const { entries } = await load()
  const key = normalize(query)
  const properNoun = /^[A-Z]/.test(query.trim())

  let matchedKey: string | null = null
  let hits: DictEntry[] = []
  if (key && entries.has(key)) {
    matchedKey = key
    hits = entries.get(key)!
  } else if (key) {
    for (const stem of stems(key)) {
      if (entries.has(stem)) {
        matchedKey = stem
        hits = entries.get(stem)!
        break
      }
    }
  }

  const ordered = [...hits].sort((a, b) => {
    if (a.source === b.source) return 0
    const biblicalFirst = properNoun
    if (a.source === "eastons") return biblicalFirst ? -1 : 1
    return biblicalFirst ? 1 : -1
  })

  return { query, matchedKey, entries: ordered }
}

function capitalize(word: string): string {
  return word.charAt(0).toUpperCase() + word.slice(1)
}

// Clean a single Webster sense for projection: drop usage examples, synonym
// lists, editorial markers, bracketed labels, and trailing author citations.
function cleanGloss(s: string): string {
  let t = s
  const dash = t.indexOf(" -- ") // Webster's example separator
  if (dash !== -1) t = t.slice(0, dash)
  t = t.replace(/\bSyn\.\s[\s\S]*$/, "") // drop "Syn. ..." synonym lists
  t = t.replace(/\bDefn:\s*/g, "").replace(/\bEtym:\s*\[[^\]]*\]/g, "")
  t = t.replace(/\[[^\]]*\]/g, "") // [Obs.], [Archaic], [Colloq.] …
  t = t.replace(/^\s*(?:pl\.|sing\.)\s*/i, "") // leading grammar label
  // Trailing author citation(s): runs of "Name." / "X." at the very end.
  t = t.replace(/(?:\s+(?:[A-Z][a-z]*\.|[A-Z]\.)){1,4}\s*$/g, "")
  return t.replace(/\s+/g, " ").trim().replace(/[;,]+$/, "").trim()
}

export interface Sense {
  // 1-based index within the entry, for display ("1.", "2.", …).
  n: number
  // The cleaned, projectable gloss.
  text: string
}

// Split a Webster entry into its discrete senses. Webster numbers senses
// sequentially (1., 2., 3. …) and may restart numbering for a new part of
// speech (separated by a blank line). We walk looking for the NEXT expected
// number so stray numerals — scripture refs ("1 Cor."), verse numbers ("13."),
// roman-numeral citations — never start a false sense. Sub-definitions (the
// "-- Barren flower, …" phrase entries) are intentionally dropped: cleanGloss
// cuts at " -- ", so only the head senses survive.
export function parseSenses(definition: string): Sense[] {
  const blocks = definition.split(/\n\n+/).map((b) => b.trim()).filter(Boolean)
  const out: string[] = []

  for (const block of blocks) {
    if (!/^1\.\s/.test(block)) {
      out.push(block) // unnumbered single-sense block
      continue
    }
    let rest = block
    let expected = 1
    // Loop: strip the current "N." prefix, then find the next " (N+1). " marker.
    while (true) {
      rest = rest.replace(new RegExp(`^${expected}\\.\\s*`), "")
      const next = new RegExp(`\\s${expected + 1}\\.\\s`)
      const m = rest.match(next)
      if (m && m.index !== undefined) {
        out.push(rest.slice(0, m.index).trim())
        rest = `${expected + 1}. ${rest.slice(m.index + m[0].length)}`
        expected += 1
      } else {
        out.push(rest.trim())
        break
      }
    }
  }

  const senses: Sense[] = []
  for (const raw of out) {
    const g = cleanGloss(raw)
    if (g.length > 1) senses.push({ n: senses.length + 1, text: g })
  }
  return senses
}

// Turn a word + chosen body text into a projectable slide. The "note-" id
// prefix makes slide-stage render it as a titled markdown slide (word heading +
// body), and lets it flow through the existing preview → go live → queue
// pipeline unchanged. `body` is the (possibly operator-edited) sense text.
export function definitionToSlide(word: string, body: string): SelectedVerse {
  return {
    id: `note-def-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
    book: "",
    chapter: 0,
    verse: 0,
    reference: capitalize(word),
    text: body.trim(),
  }
}

// Prefix suggestions for the pane's type-ahead. Returns display words.
export async function suggest(prefix: string, limit = 8): Promise<string[]> {
  const { entries, keys } = await load()
  const p = normalize(prefix)
  if (!p) return []
  const out: string[] = []
  // keys is sorted, so a linear scan from the first prefix match is fine for
  // the small `limit` we ask for.
  let started = false
  for (const k of keys) {
    if (k.startsWith(p)) {
      started = true
      // Prefer the Easton display word (proper case) when present.
      const list = entries.get(k)!
      const easton = list.find((e) => e.source === "eastons")
      out.push(easton ? easton.word : k)
      if (out.length >= limit) break
    } else if (started) {
      break // past the prefix block in sorted order
    }
  }
  return out
}
